[package]
name = "rusTracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font8x8 = "0.3.1"
pollster = "0.3.0"
wgpu = "23.0.0"
ascii = "1.1.0"
winit = "0.30.4"
tracker-engine = { git = "https://github.com/luca3s/tracker-engine" }
# symphonia = "0.5.4"

[profile.dev]
debug = 0
panic = "unwind"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
