[package]
name = "RustRacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.15.0"
# anyhow = "1.0.75"
# arrayvec = "0.7.4"
# basedrop = "0.1.2"
# cpal = "0.15.2"
# env_logger = "0.10.0"
font8x8 = "0.3.1"
pollster = "0.3.0"
tap = "1.0.1"
# terrors = "0.2.6" look at it for OneOf Type
# rtrb = "0.2.3"
wgpu = "0.19.3"
winit = "0.29.15"
