[package]
name = "rusTracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font8x8 = "0.3.1"
wgpu = "23.0.0"
ascii = "1.1.0"
winit = "0.30.5"
tracker-engine = { git = "https://github.com/luca3s/tracker-engine" }
smol = "2.0.2"
paste = "1.0.15"
# widget_list_derive = { version = "0.1.0", path = "../widget_list_derive" }
# symphonia = "0.5.4"

# [profile.dev]
# debug = 0
# panic = "unwind"

# [profile.release]
# strip = true
# lto = true
# codegen-units = 1
# panic = "abort"
