[package]
name = "RustRacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
font8x8 = "0.3.1"
pixels = "0.13.0"
winit = "0.28.7"
