[package]
name = "rusTracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# anyhow = "1.0.75"
# basedrop = "0.1.2"
# cpal = "0.15.3"
# env_logger = "0.10.0"
font8x8 = "0.3.1"
pollster = "0.3.0"
# rtrb = "0.2.3"
wgpu = "0.19.4"
ascii = "1.1.0"
winit = "0.29.15"
left-right = "0.11.5"
# lockfree = "0.5.1"
# symphonia = "0.5.4"
# knyst = { version = "0.5.0", features = ["debug-warn-on-alloc", "cpal"], default_features = false }

[profile.dev]
debug = 0
panic = "unwind"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
